# Generated by Django 5.2.7 on 2025-11-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=129)),
                ('created_date', models.IntegerField()),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=30)),
                ('number_of_views', models.IntegerField()),
            ],
        ),
    ]
